{
 "title": "Anon IRC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": "thewired" }
  ]
 },
 "panels": [
  {
   "title": "Incoming Message Processing Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(message_processing_seconds_sum{instance=\"$instance:8000\"}[1m] offset 150s)",
     "legendFormat": "1m-rate"
    },
    {
     "expr": "rate(message_processing_seconds_sum{instance=\"$instance:8000\"}[5m])",
     "legendFormat": "average"
    },
    {
     "expr": "version_info{instance=\"$instance:8000\"} offset 150s",
     "legendFormat": "git {{version}}"
    }
   ]
  },
  {
   "title": "Messages per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(messages_total{instance=\"$instance:8000\"}[1h])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Messages per week",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(messages_total{instance=\"$instance:8000\"}[1w])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "clients_connected{instance=\"$instance:8000\"}",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Request types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_total{instance=\"$instance:8000\"}[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Channel members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_members{instance=\"$instance:8000\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Message handling errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(request_error_total{instance=\"$instance:8000\"}[5m])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Time to send a message to clients",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(msg_send_seconds_sum{instance=\"$instance:8000\"}[30s])",
     "legendFormat": "irate"
    },
    {
     "expr": "rate(msg_send_seconds_sum{instance=\"$instance:8000\"}[5m])",
     "legendFormat": "average"
    }
   ]
  }
 ]
}