#!/usr/bin/env python3

import argparse
import asyncio
import importlib
import signal
import ssl

from prometheus_client import start_http_server

import reloadable

clients = []
current_version = None


class Client:
    def __init__(self, writer):
        self.writer = writer
        self.channels = set()


def reload():
    global current_version
    print("reloading reloadable.py")
    importlib.reload(reloadable)
    current_version = reloadable.reload(clients, current_version=current_version)


async def handle(reader, writer):
    client = Client(writer)
    clients.append(client)
    reloadable.on_client_connect(client, clients)
    try:
        reloadable.Client(client).send_ping()
        while True:
            data = await reader.readuntil(b"\r\n")
            reloadable.process_message(data, client, clients)
            await writer.drain()
    finally:
        clients.remove(client)
        reloadable.on_client_disconnect(client, clients)
        writer.close()


async def irc_main(port):
    server = await asyncio.start_server(handle, "0.0.0.0", port)
    addr = server.sockets[0].getsockname()
    print(f"serving on {addr}")
    await server.serve_forever()


async def ssl_irc_main(port, fullchain, privkey):
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    ssl_context.load_cert_chain(certfile=fullchain, keyfile=privkey)

    server = await asyncio.start_server(handle, "0.0.0.0", port, ssl=ssl_context)
    addr = server.sockets[0].getsockname()
    print(f"serving ssl on {addr}")
    await server.serve_forever()


parser = argparse.ArgumentParser()
parser.add_argument("--fullchain", default=None)
parser.add_argument("--privkey", default=None)
parser.add_argument("--irc-port", type=int, default=6667)
parser.add_argument("--irc-ssl-port", type=int, default=6697)
parser.add_argument("--metrics-port", type=int, default=8000)

args = parser.parse_args()

loop = asyncio.get_event_loop()
loop.create_task(irc_main(args.irc_port))

if args.fullchain and args.privkey:
    loop.create_task(ssl_irc_main(args.irc_ssl_port, args.fullchain, args.privkey))

loop.add_signal_handler(signal.SIGHUP, reload)
reload()

start_http_server(args.metrics_port)

loop.run_forever()
