#!/usr/bin/env python3

import asyncio
import sys

import aioredis

loop = asyncio.get_event_loop()


async def main(channel, msg):
    stream = "msgs"
    fields = {b"user": 0, b"channel": channel, b"msg": msg}

    redis = await aioredis.create_redis("redis://localhost", loop=loop)
    result = await redis.xadd(stream, fields)
    print(result)
    redis.close()
    await redis.wait_closed()

channel = sys.argv[1]
msg = sys.argv[2]

loop.run_until_complete(main(channel, msg))
